import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="h-12 m-2 bg-indigo-600/80 flex items-center p-2 rounded text-white inset-shadow-sm inset-shadow-indigo-200">
          <h1 className="text-2xl font-bold">Damien&apos;s Blog</h1>
        </nav>
        {children}
      </body>
    </html>
  );
}
